### ISSUE TITLE
Hedera Hashgraph File System smart contract standard

### ISSUE THREAD

**Issue by publu** [hashgraph/hedera-improvement-proposal#16]
Description:
HRC contract specification for a file routing mechanism. It functions as a web routing mechanism for the File Services within Hedera Hashgraph. ie: route "/" to fileID
Hedera Improvement Proposal: Not Required
Primary Contact (assignee): @publu 

more info: https://twitter.com/itspublu/status/1193952250059640832

**Comment by Cooper-Kunz** [comment]
Hey Pablo! Super interesting idea. 

It's asked in the example template we're close to finalizing, but what is your main goal for this?

Have you thought about how this could use a p2p storage solution like IPFS? Perhaps Hedera's File Service would be better used as a "lookup table" for IPFS, rather than used to host the actual files themselves? e.g. store the `main.js` in your image below in IPFS and save the IPFS ref on Hedera.

![image](https://user-images.githubusercontent.com/11776938/68719804-5ccf8e80-056a-11ea-9ea4-e8f7f938122e.png)

[Image from Pablo's twitter](https://twitter.com/itspublu/status/1193957135823953922?s=20)

**Comment by publu** [comment]
HFS would serve as an initial layer controlled by the end user much like a web server

The value record could begin with "fd://{fileid}" so that we could include other values like ipfs ie: ipfs://

**Comment by Cooper-Kunz** [comment]
That seems to make sense. So to clarify, is your goal to provide a single smart contract standard that simply looks up and returns content from multiple files, or is it to explicitly act as a web server of sorts and have additional functionality/standards focused on that use case?

**Comment by publu** [comment]
It would be a bit of both actually. Surface level it would look up and return fileid/ipfs routing values. It would also provide extra routing like error pages and automatically return index file

**Comment by bwonymph** [comment]
Does Hedera have a standard for the file hashing for HFS? This would standardize the identifiers to be used for lookup.

**Comment by kenthejr** [comment]
We love your input. If you still would like to pursue this as an improvement, please submit a Hedera Improvement Proposal in accordance with [hip-1](https://github.com/hashgraph/hedera-improvement-proposal/blob/master/HIP/hip-1.md). If no further action is taken within 7 days, this issue will be closed.
